### ISSUE TITLE
no camera movment

### ISSUE THREAD

**Issue by HENRI067** [HENRI067/2d-game#1]
the camera movement will need its own script, since putting the Main camera as the child of the player will make the camera be fliped when the script flips the player sprite to the direction he is moving

**Comment by JordanOrtizTheDev** [comment]
Ok. To start, would you like the parent to be able to rotate in-game? Also, are you currently using a rigid body 2d as the controller? You can just check some boxes in the constraints options.

**Comment by JordanOrtiz** [comment]
Or if you're not using a rigid body you could have a script that makes the camera move by checking the parents x and y values and moving its values by the same thing. Here's what I got:

`//variables and references
public Transform ParentTransform; //or change it to something else idk
public Transform CameraTransform;

//functions 
public void Start()
{
    CameraTransform.position(ParentTransform, ParentTransform);
}`

I wouldn't count on this working though.
